export const LOGIN = 'LOGIN';
export const FETCH_DOCTORS = 'FETCH_DOCTORS';
export const FETCH_PATIENTS = 'FETCH_PATIENTS';
export const FETCH_PHARMACISTS = 'FETCH_PHARMACISTS';
export const FETCH_STAFF_MEMBERS = 'FETCH_STAFF_MEMBERS';
export const LOGIN_TO_PATIENT = 'LOGIN_TO_PATIENT';
export const GET_MY_PRESCRIPTIONS = 'GET_MY_PRESCRIPTIONS';
